apiVersion: v1
kind: Namespace
metadata:
  name: mtd
---  # privilege settings for controlling the cluster from within pod
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mtd-sa
  namespace: mtd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mtd-cr
  namespace: mtd
rules:
  - apiGroups: ["", "apps", "metrics.k8s.io"]
    resources: ["pods", "deployments", "services", "nodes"]
    verbs: ["delete", "get", "create", "patch", "list", "update"]
# TODO: split rules up to minimize privilege
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mtd-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mtd-cr
subjects:
  - kind: ServiceAccount
    name: mtd-sa
    namespace: mtd
---  # resources for the zookeeper ensemble and the mtd coordination containers
apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  labels:
    app: mtd-zk
  namespace: mtd
spec:
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  clusterIP: None
  selector:
    app: mtd-zk
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  labels:
    app: mtd-zk
  namespace: mtd
spec:
  ports:
    - port: 2181
      name: client
  selector:
    app: mtd-zk
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
  namespace: mtd
spec:
  selector:
    matchLabels:
      app: mtd-zk
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mtd-zk
  namespace: mtd
spec:
  selector:
    matchLabels:
      app: mtd-zk
  serviceName: zk-hs
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: mtd-zk
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - mtd-zk
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: mtd-coordinator
          image: docker.io/mtd-zk:kind  # kind settings
          imagePullPolicy: Never  # kind settings
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        - name: zookeeper
          imagePullPolicy: Always
          image: "registry.k8s.io/kubernetes-zookeeper:1.0-3.4.10" # BEWARE: old server version
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
          command:
            - sh
            - -c
            - "start-zookeeper \
              --servers=3 \
              --data_dir=/var/lib/zookeeper/data \
              --data_log_dir=/var/lib/zookeeper/data/log \
              --conf_dir=/opt/zookeeper/conf \
              --client_port=2181 \
              --election_port=3888 \
              --server_port=2888 \
              --tick_time=2000 \
              --init_limit=10 \
              --sync_limit=5 \
              --heap=512M \
              --max_client_cnxns=60 \
              --snap_retain_count=3 \
              --purge_interval=12 \
              --max_session_timeout=40000 \
              --min_session_timeout=4000 \
              --log_level=INFO"
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "zookeeper-ready 2181"
            initialDelaySeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "zookeeper-ready 2181"
            initialDelaySeconds: 10
            timeoutSeconds: 5
      serviceAccountName: mtd-sa
      restartPolicy: Always
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
# YAML file modified from https://k8s.io/examples/application/zookeeper/zookeeper.yaml
